

#include "COMobjects_h.h" // Generated by MIDL
#include "COMobjects.h"
#include "Csum.h"



ULONG Csum::AddRef()
{
    return ++m_cRef;
}

ULONG Csum::Release()
{
    if(--m_cRef != 0)
        return m_cRef;
    delete this;
    return 0;
}

HRESULT Csum::QueryInterface(REFIID riid, void** ppv)
{
    if(riid == IID_IUnknown)
        *ppv = (IUnknown*)this;
    else if(riid == IID_ISum)
        *ppv = (ISum*)this;
    else
    {
        *ppv = NULL;
        return E_NOINTERFACE;
    }
    AddRef();
    return S_OK;
}

HRESULT Csum::Sum(int x, int y, int* retval)

{
    *retval = x + y;
    return S_OK;
}







ULONG CsumFactory::AddRef()
{
    return ++m_cRef;
}

ULONG CsumFactory::Release()
{
    if(--m_cRef != 0)
        return m_cRef;
    delete this;
    return 0;
}

HRESULT CsumFactory::QueryInterface(REFIID riid, void** ppv)
{
    if(riid == IID_IUnknown)
        *ppv = (IUnknown*)this;
    else if(riid == IID_IClassFactory)
        *ppv = (IClassFactory*)this;
    else
    {
        *ppv = NULL;
        return E_NOINTERFACE;
    }
    AddRef();
    return S_OK;
}

HRESULT CsumFactory::CreateInstance(IUnknown *pUnknownOuter, 
    REFIID riid, void** ppv)
{
    if(pUnknownOuter != NULL)
        return CLASS_E_NOAGGREGATION;

    Csum *pInsideCOM = new Csum;
    if(pInsideCOM == NULL)
        return E_OUTOFMEMORY;

    HRESULT hr = pInsideCOM->QueryInterface(riid, ppv);
    pInsideCOM->Release();
    return hr;
}

HRESULT CsumFactory::LockServer(BOOL bLock)
{
    if(bLock)
        g_com_cLocks++;
    else
        g_com_cLocks --;
    return S_OK;
}




