//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by main.rc
//
#define CREATEPROCESS_MANIFEST_RESOURCE_ID 1
#define IDS_UNINST_1                    1
#define IDS_UNINST_CAP                  2
#define IDC_ID3_REMOVE                  3
#define IDS_UNINST_CANCEL               3
#define IDC_NEVER                       3
#define IDS_UNINST_SURE                 4
#define IDS_ERRORINIT                   5
#define IDS_EQCAPTION                   6
#define IDS_PECAPTION                   7
#define IDS_OPENDIR                     8
#define IDS_OPENDIRMORE                 9
#define IDS_PLUGINERROR                 10
#define IDS_ERRORLOADINGPLUGIN          11
#define IDS_DYNAMICLINKS                12
#define IDS_DLINK_UPDATE                13
#define IDS_PREFS_BOOK                  13
#define IDS_DLINK_NOCONTENT             14
#define IDS_DLINK_GETTING               15
#define IDS_DLINK_SUCCESS               16
#define IDS_DLINK_ERROR                 17
#define IDS_UNREGSTRING                 18
#define IDS_STATS                       19
#define IDS_ONLYHTTP                    20
#define IDS_NOOUTPUT                    21
#define IDS_PLAYLISTSTRING              22
#define IDS_ALLTYPES                    23
#define IDS_RETRPL                      24
#define IDS_CONF_HELPSTR                25
#define IDS_P_IN_INPUTS                 26
#define IDS_P_IN_CONF                   27
#define IDS_P_IN_ABOUT                  28
#define IDS_P_O_DEFEXT                  29
#define IDS_P_SETUP_PROXY               30
#define IDS_P_OUT_CONF                  31
#define IDS_P_OUT_ABOUT                 32
#define IDS_P_OUT_OUTPUTS               33
#define IDS_P_O_PRIO                    34
#define IDS_P_SETUP_PRIO                34
#define IDS_P_DISP_SYSTRAY              35
#define IDS_P_DISP_TASKBAR              36
#define IDS_P_DISP_SYSTRAYICON          37
#define IDS_P_DISP_SYSTRAYTASK          38
#define IDS_P_DISP_FREESIZE             38
#define IDS_P_DISP_NONE                 39
#define IDS_P_CLASSICUI                 39
#define IDS_P_DISP_HILITE               40
#define IDS_P_DISP_SNAP                 41
#define IDS_P_DISP_CB                   42
#define IDS_P_DISP_TTIPS                43
#define IDS_P_O_SPLASH                  44
#define IDS_P_DISP_TNUMS                45
#define IDS_P_O_PLCHILD                 46
#define IDS_P_O_SPLB                    46
#define IDS_P_O_EQDS                    47
#define IDS_P_DISP_CURSORS              48
#define IDS_P_O_ONLOAD                  49
#define IDS_P_O_ONDEM                   50
#define IDS_P_O_RFL                     51
#define IDS_P_O_AMI                     52
#define IDS_P_SETUP_MINST               52
#define IDS_P_O_CONVERT1                53
#define IDS_P_O_CONVERT2                54
#define IDS_P_DISP_STITLE               55
#define IDS_P_DISP_PLFONT               56
#define IDS_P_O_LITESTEP                57
#define IDS_P_O_AOVD                    58
#define IDS_P_FT_EXTENSIONS             59
#define IDS_P_FT_ALL                    60
#define IDS_P_FT_NO                     61
#define IDS_P_FT_ENQUEUE                62
#define IDS_P_FT_ICON                   63
#define IDS_P_FT_ICON2                  64
#define IDS_P_SETUP_START               65
#define IDS_PREFSHLP_FT_DESK            66
#define IDS_P_VIS_LIB                   67
#define IDS_P_VIS_MOD                   68
#define IDS_P_PLUG_AUTO                 69
#define IDS_P_PLUG_DIS                  70
#define IDS_P_VIS_START                 71
#define IDS_P_VIS_STOP                  72
#define IDS_P_VIS_CONF                  73
#define IDS_P_PLUG_PRIO                 74
#define IDS_P_DSP_LIB                   75
#define IDS_P_DSP_MOD                   76
#define IDS_P_DSP_CONF                  77
#define IDS_P_GEN_LIB                   78
#define IDS_P_GEN_CONF                  79
#define IDS_P_PLUG_FLUSH                80
#define IDS_TOOLTIPS                    81
#define IDS_P_SETUP_START2              82
#define IDS_P_SETUP_LANG                83
#define IDS_P_FT_DIRCONTEXT             84
#define IDS_P_DISP_SNAPW                85
#define IDS_P_PLUG_VISDIR               86
#define IDS_P_PLUG_DSPDIR               87
#define IDS_SELVISDIR                   88
#define IDS_SELDSPDIR                   89
#define IDS_PREFS_SETUP                 90
#define IDS_PREFS_FT                    91
#define IDS_PREFS_OPTIONS               92
#define IDS_PREFS_WINAMPPRO             92
#define IDS_PREFS_DISPLAY               93
#define IDS_PREFS_TITLES                93
#define IDS_PREFS_PLUG                  94
#define IDS_PREFS_PLUG_IN               95
#define IDS_PREFS_PLUG_OUT              96
#define IDS_PREFS_PLUG_VIS              97
#define IDS_PREFS_PLUG_DSP              98
#define IDS_PREFS_PLUG_GEN              99
#define IDS_P_FT_CD                     100
#define WINAMP_MAIN                     101
#define IDS_MBCAPTION                   101
#define ICON_XP                         102
#define IDS_INETLOC                     102
#define IDD_BUFFERS                     103
#define IDS_PERMDELALL                  103
#define IDD_OUTPUT                      104
#define IDS_LANGCHANGE                  104
#define IDS_SELLANGPACK                 105
#define IDS_DELETEAUTOLOAD1             106
#define IDS_DELETEAUTOLOAD2             107
#define IDS_DELETEPRE1                  108
#define IDB_SPLASH                      109
#define IDS_LOADAUTOLOAD                109
#define IDD_SPLASH                      110
#define IDS_SAVEAUTOLOAD                110
#define IDS_PLFONT                      111
#define IDS_PLFONT_CHARSET              112
#define IDS_P_FT_RSTART                 113
#define IDS_P_DISP_BIFONT               114
#define IDS_GETMORE                     115
#define IDD_PREFS                       116
#define IDS_INST_DONETITLE              116
#define IDS_INST_SETTITLE               117
#define IDS_INST_USERINFO               118
#define IDS_INST_LATER                  119
#define IDD_ABOUT1                      120
#define IDS_INST_SENDINGIN              120
#define IDD_NEWABOUT1                   120
#define IDS_INST_FINISH                 121
#define IDS_INST_INET1                  122
#define IDS_INST_INET2                  123
#define IDS_INST_INET3                  124
#define IDS_INET_CANCEL1                125
#define IDB_MAINBITMAP                  126
#define IDS_P_SETUP_VER                 126
#define IDB_CBUTTONS                    127
#define IDS_P_SETUP_ADDQL               127
#define IDS_P_SETUP_INTERNET            127
#define IDB_MONOSTEREO                  128
#define IDS_P_SETUP_INET1               128
#define IDB_PLAYPAUSE                   129
#define IDS_P_SETUP_INET2               129
#define IDB_SHUFFLEREP                  130
#define IDS_P_SETUP_INET3               130
#define IDI_FILEICON                    131
#define IDS_DSP_NONE                    131
#define IDB_NUMBERS1                    132
#define IDS_CONFIG_PLAYSTR              132
#define IDB_VOLBAR                      133
#define IDS_CONFIG_ENQUEUESTR           133
#define IDB_FONT1                       134
#define IDS_PREFS_SKIN                  134
#define IDB_POSBAR                      135
#define IDS_P_O_MPA                     135
#define IDS_P_SK_SEL                    136
#define IDS_P_SK_RND                    137
#define IDS_P_SK_CHDR                   138
#define IDS_PREFS_VIS                   139
#define IDS_PREFS_CLASSICSKIN           139
#define IDS_PREFS_AG                    140
#define IDD_EQ                          141
#define IDS_P_SETUP_VER2                141
#define IDD_PLAYLISTEDITOR              142
#define IDS_P_A_ENABLE                  142
#define IDS_P_A_TRAY                    143
#define IDD_FILETYPES                   144
#define IDS_P_FILEASSOCIATIONS          144
#define IDD_VIS                         145
#define IDS_CONFIG_BOOKMARKSTR          145
#define IDS_P_O_ONPLAY                  146
#define IDS_P_O_SMS                     147
#define IDR_ACCELERATOR1                148
#define IDS_PREFS_SHUFFLE               148
#define IDB_SPEC                        149
#define IDS_VIDEOCAPTION                149
#define IDB_TB                          150
#define IDS_PREFS_VIDEO                 150
#define IDS_P_O_VIDEO_VSYNC             151
#define IDD_ABOUT2                      152
#define IDS_P_O_VIDEO_ADJASP            152
#define IDB_NULLSOFT                    153
#define IDS_P_O_VIDEO_OVERLAYS          153
#define IDD_ABOUT3                      154
#define IDD_NEWABOUT2                   154
#define IDS_P_O_VIDEO_UPDSIZE           154
#define IDD_ABOUT4                      155
#define IDS_P_O_VIDEO_AUTOCLOSE         155
#define IDD_ABOUT5                      156
#define IDS_P_O_VIDEO_NOSS              156
#define IDD_ABOUT6                      157
#define IDS_P_O_VIDEO_OSD               157
#define IDR_ACCELERATOR2                158
#define IDS_P_O_VIDEO_YV12              158
#define IDS_P_O_VIDEO_STOPCLOSE         159
#define IDS_P_O_VIDEO_REMOVE_FS_ON_STOP 160
#define IDD_DISPLAY                     161
#define IDS_P_O_VIDEO_AUTOOPEN          161
#define IDI_FILEICON2                   162
#define IDS_P_CLASSICVIS                162
#define IDI_FILEICON3                   163
#define IDS_P_IN_UNINST                 163
#define IDI_FILEICON10                  164
#define IDS_P_VIS_UNINST                164
#define IDD_ID3EDIT                     165
#define IDS_P_OUT_UNINST                165
#define IDS_P_SKINS_DELETESKIN          166
#define IDI_FILEICON5                   167
#define IDS_P_SKINS_DELETESKIN_PROMPT   167
#define IDS_P_O_VIDEO_AGRESSIVENOSS     168
#define IDI_FILEICON6                   169
#define IDS_P_PLUG_DISSEHVIS            169
#define IDS_P_PLUG_DISSEHDSP            170
#define IDS_P_PLUG_DISSEHGEN            171
#define IDD_LOADPRESET                  173
#define IDD_SAVEPRESET                  174
#define IDR_ACCELERATOR3                175
#define IDD_OPENLOC                     176
#define IDR_ACCELERATOR4                176
#define IDD_HTTP                        177
#define IDI_FILEICON7                   178
#define IDD_PLUGIN                      178
#define IDI_FILEICON8                   179
#define IDI_FILEICON9                   180
#define IDI_FILEICON4                   181
#define IDI_FILEICON11                  182
#define IDI_FILEICON12                  183
#define IDD_JUMPDLG                     184
#define IDD_JUMPFILEDLG                 185
#define IDD_ABOUT7                      188
#define IDD_SKINS                       189
#define IDD_PLUGIN2                     190
#define IDR_PLMENU                      191
#define IDC_REGDLG                      191
#define IDD_EDITENTRY                   192
#define IDD_OPTIONS                     193
#define IDB_EQMAIN                      194
#define IDB_PANBAR                      197
#define IDB_PLEDIT                      199
#define IDC_MOVEMAIN                    205
#define IDC_LRSCROLL                    206
#define IDC_DANGER                      207
#define IDC_NORMALCURSOR                208
#define IDC_UDSCROLL                    209
#define IDB_ME                          210
#define IDC_RESIZE                      210
#define IDB_CAT                         212
#define IDD_HTTPGET                     214
#define IDD_NEWPREFS                    215
#define IDD_NEWSETUP                    216
#define IDD_NEWFTYPES                   217
#define IDD_NEWOPTIONS                  218
#define IDD_NEWDISPLAY                  219
#define IDD_NEWPLUG                     221
#define IDD_NEWINPUT                    222
#define IDD_NEWOUTPUT                   223
#define IDD_NEWVIS                      224
#define IDD_NEWDSP                      225
#define IDD_NEWGEN                      226
#define IDD_OPENLOCMB                   227
#define IDB_MB                          228
#define IDD_METRIC1                     230
#define IDD_FIRSTSETUP                  231
#define IDB_EQEX                        231
#define IDD_FS_FILES                    233
#define IDD_FS_REG                      234
#define IDD_FS_REG2                     235
#define IDD_NEWSKIN                     236
#define IDD_NEWVIS2                     237
#define IDD_CLASSIC_VIS                 237
#define IDD_ABOUT8                      238
#define IDD_NEWAGENT                    239
#define IDD_NEWBOOKMARKS                240
#define IDI_UNINST                      240
#define IDD_EDITBOOKMARK                241
#define IDB_BITMAP1                     242
#define IDD_NEWABOUT3                   243
#define IDB_BITMAP2                     243
#define IDD_NEWABOUT4                   244
#define IDD_NEWABOUT                    245
#define IDD_NEWSHUFFLEOPTS              246
#define IDD_NEWVIDEOOPTS                247
#define IDB_VIDEOLOGO                   248
#define IDB_VIDEO                       249
#define IDB_EMBEDWND                    250
#define IDB_GENEX                       252
#define IDD_CONVERT_WAV                 253
#define IDB_TEAM                        254
#define IDD_NEWREG                      254
#define IDD_BURN                        255
#define IDD_EDITREG                     256
#define WINAMP5_MENUBAR                 256
#define IDD_PREFS_CLASSICSKIN           257
#define IDD_CLASSIC_UI                  258
#define IDD_NEWTITLE                    259
#define IDD_RENAMESKIN                  260
#define IDD_BROWSE_RECDLG               261
#define ICON_TB1                        262
#define IDC_BUFFERS_NUMBUFS             1001
#define IDC_8BIT                        1004
#define IDC_16BIT                       1005
#define IDC_PREFS_SPLASH                1006
#define IDC_WA_CURSORS                  1007
#define IDC_PREFS_SYSTRAY               1008
#define IDC_PREBUFSLIDER                1011
#define IDC_ALLOWMI                     1013
#define IDC_FORMAT                      1014
#define IDC_RFL                         1015
#define IDC_USEID3                      1015
#define IDC_REGFILETYPES                1016
#define IDC_MINST                       1016
#define IDC_USEID4                      1017
#define IDC_USEID5                      1018
#define IDC_EQ1                         1019
#define IDC_EQ2                         1020
#define IDC_EQ3                         1021
#define IDC_EQ4                         1022
#define IDC_EQ5                         1023
#define IDC_EQ6                         1024
#define IDC_EQ7                         1025
#define IDC_EQ8                         1026
#define IDC_EQ9                         1027
#define IDC_EQ10                        1028
#define IDC_EQ_ENABLED                  1029
#define IDC_EQ_CLOSE                    1030
#define IDC_PLAYLIST_LISTBOX            1031
#define IDC_EQ_RESET                    1031
#define IDC_EQ11                        1031
#define IDC_TAGZ_HELP                   1031
#define IDC_PLAYLIST_ADDMP3             1032
#define IDC_EQ_ZERO                     1032
#define IDC_PLAYLIST_ADDPLAYLIST        1033
#define IDC_PLAYLIST_REMOVEMP3          1034
#define IDC_PLAYLIST_CROP               1035
#define IDC_TAGZ_DEFAULT                1035
#define IDC_PLAYLIST_ADDDIR             1036
#define IDC_PLAYLIST_CLEAR              1037
#define IDC_PLAYLIST_EDITID3            1038
#define IDC_PLAYLIST_ADDLOC             1039
#define ID_PE_REMOVE                    1041
#define IDC_AUTOSCROLL                  1041
#define IDC_PLAYLIST_MOVEBAR            1042
#define IDC_SA                          1043
#define IDC_OSC                         1044
#define IDC_NOVIS                       1045
#define IDC_STEREO                      1046
#define IDC_MONO                        1047
#define IDC_REVSTEREO                   1048
#define IDC_FULLRATE                    1049
#define IDC_HALFRATE                    1050
#define IDC_AMP_README                  1054
#define IDC_OUTPUTDEV                   1056
#define IDC_EQVOL                       1058
#define IDC_PLAYLIST_SORT               1059
#define IDC_PLAYLIST_INVERT             1060
#define IDC_PLAYLIST_REVERSE            1061
#define IDC_PLAYLIST_LOADLIST           1062
#define IDC_PLAYLIST_SAVELIST           1063
#define IDC_ENC_CONFIG                  1063
#define IDC_SPECFALLOFF                 1064
#define IDC_PLAYLIST_RANDOMIZE          1064
#define IDC_SPECREFRESH                 1065
#define IDC_SPECSCALE                   1066
#define IDC_TASKBAR                     1067
#define IDC_SYSTRAY                     1068
#define IDC_SYSTRAYANDTASK              1069
#define IDC_OSCSCALE                    1070
#define IDC_NONE                        1070
#define IDC_FILETYPES_ICONSCROLL        1073
#define IDC_PREFS_PRIORITY_CLASS        1074
#define IDC_FILETYPES_ICONSCROLL2       1074
#define IDC_PREFS_PRIORITY_OUTPUT       1075
#define IDC_PREFS_PRIORITY_DECODE       1076
#define IDC_FILETYPES_ICON              1077
#define IDC_ID3_TITLE                   1078
#define IDC_FILETYPES_ICON2             1078
#define IDC_ID3_ARTIST                  1079
#define IDC_ID3_ALBUM                   1080
#define IDC_ID3_COMMENT                 1081
#define IDC_ID3_YEAR                    1082
#define IDC_ID3_GENRE                   1083
#define IDC_ID3_FN                      1084
#define IDC_EQ_SAVE                     1090
#define IDC_EQ_SAVEMPX                  1091
#define IDC_EQ_DELETE                   1092
#define IDC_EQ_LOAD                     1093
#define IDC_EQ_PRESET                   1094
#define IDC_EQ_AUTOLOAD                 1095
#define IDC_PE_TIME                     1096
#define IDC_LOADEQLIST                  1099
#define IDC_SAVEPRESET_EDIT             1101
#define IDC_NORMALANALYZER              1102
#define IDC_SPLASHIMG                   1103
#define IDC_FIREANALYZER                1103
#define IDC_BUFFER_ALL                  1104
#define IDC_LINEANALYZER                1104
#define IDC_BUF_SFAST                   1106
#define IDC_SNAP                        1108
#define IDC_ADDSTART                    1109
#define IDC_MAINPARENT                  1109
#define IDC_REMSTART                    1110
#define IDC_URL                         1110
#define IDC_HIGHLIGHT                   1110
#define IDC_ADDICON                     1110
#define IDC_SAVE                        1111
#define IDC_ADDDESKTOP                  1111
#define IDC_VOLUMEENABLED               1112
#define IDC_ADDQL                       1112
#define IDC_PANREV                      1113
#define IDC_VISLIB                      1113
#define IDC_VISMOD                      1114
#define IDC_ALTVOL                      1114
#define IDC_VISTEST                     1115
#define IDC_VISCONF                     1116
#define IDC_VISPRIO                     1117
#define IDC_SNDLIB                      1118
#define IDC_BLOCKSIZE                   1118
#define IDC_DSPLIB                      1118
#define IDC_VISSTOP                     1118
#define IDC_MPEGINFO                    1119
#define IDC_DSPMOD                      1119
#define IDC_MINUTES                     1120
#define IDC_DSPCONF                     1120
#define IDC_SECONDS                     1121
#define IDC_GENLIB                      1121
#define IDC_TRACKLEN                    1122
#define IDC_SELBOX                      1122
#define IDC_GENCONF                     1122
#define IDC_AUTOEXEC                    1123
#define IDC_OUTPUTINTERP                1124
#define IDC_HQ                          1125
#define IDC_DISVIS                      1126
#define IDC_ID3FORMAT                   1127
#define IDC_TIPS                        1128
#define IDC_PLAYLIST_BOX                1129
#define IDC_ADD_BOX                     1130
#define IDC_REMOVE_BOX                  1131
#define IDC_LENGTHTEXT                  1132
#define IDC_MISC_BOX                    1133
#define IDC_SYSTRAY_ICON                1134
#define IDC_SYSTRAY_SCROLLER            1135
#define IDC_BUFMAX                      1136
#define IDC_CLUTTERBAR                  1137
#define IDC_ADDFILES                    1138
#define IDC_DIRCONTEXT                  1139
#define IDC_SM                          1140
#define IDC_PLUGINLINK                  1141
#define IDC_SM2                         1141
#define IDC_WINAMPLINK                  1142
#define IDC_PLUGINLINK2                 1142
#define IDC_SM3                         1142
#define IDC_WINAMPLINK2                 1143
#define IDC_WINAMPLINK3                 1144
#define IDC_AFTERSEEK                   1144
#define IDC_WINAMPLINK4                 1145
#define IDC_RESIZETHINGY                1145
#define IDC_WINAMPLINK5                 1146
#define IDC_PE_ADD                      1146
#define IDC_WINAMPLINK6                 1147
#define IDC_WINAMPLINK7                 1148
#define IDC_NEWDLG                      1148
#define IDC_TTIPS                       1148
#define IDC_WINAMPLINK9                 1149
#define IDC_PROXYSTR                    1149
#define IDC_RANDOM                      1150
#define IDC_WINAMPLINK8                 1150
#define IDC_INPUTS                      1151
#define IDC_CONF                        1152
#define IDC_ABOUT                       1153
#define IDC_ABOUTTEXT                   1153
#define IDC_DEFEXT                      1154
#define IDC_ABOUT3                      1154
#define IDC_UNINSTDSP                   1154
#define IDC_LICINFO                     1155
#define IDC_OUTCONF                     1155
#define IDC_FTYPE_LIST                  1156
#define IDC_OUTABOUT                    1156
#define IDC_CONF2                       1156
#define IDC_USEINFO                     1156
#define IDC_SELALL                      1157
#define IDC_ABOUT2                      1157
#define IDC_SELNONE                     1158
#define IDC_ABOUTIMG                    1159
#define IDC_CHDIR                       1160
#define IDC_SELALL2                     1161
#define IDC_BUTTON1                     1162
#define IDC_SELALL3                     1162
#define IDC_NAME                        1163
#define IDC_BUTTON4                     1163
#define IDC_REG                         1164
#define IDC_OUTPLUG                     1164
#define IDC_BUTTON5                     1164
#define IDC_EDITBOOK                    1165
#define IDC_OLD                         1167
#define IDC_NEW                         1168
#define IDC_PLNUMS                      1168
#define IDC_PLCHILD                     1169
#define IDC_EQDSIZE                     1170
#define IDC_OUTPUTS                     1171
#define IDC_CONVERT1                    1172
#define IDC_CONVERT2                    1173
#define IDC_TREE1                       1173
#define IDC_SCROLLTITLE                 1174
#define IDC_UPDATE                      1175
#define IDC_NIFTY                       1175
#define IDC_KEEPONSCREEN                1175
#define IDC_FLUSHCACHE                  1176
#define IDC_PLFONTSIZE                  1177
#define IDC_PLFONTSIZE_TEXT             1178
#define IDC_AOVD                        1179
#define IDC_SNAPW                       1180
#define IDC_STATUS                      1180
#define IDC_MANUALPLAYLISTADVANCE       1180
#define IDC_STATUS2                     1181
#define IDC_RADIO1                      1182
#define IDC_INET1                       1182
#define IDC_INET2                       1183
#define IDC_CHLANG                      1184
#define IDC_INET3                       1185
#define IDC_RECT                        1186
#define IDC_DSPDIR                      1188
#define IDC_VISDIR                      1189
#define IDC_CD                          1193
#define IDC_RSTART                      1194
#define IDC_ALLTYPES                    1194
#define IDC_FIRSTNAME                   1195
#define IDC_LASTNAME                    1196
#define IDC_AGE                         1197
#define IDC_COUNTRY                     1198
#define IDC_GENDER                      1199
#define IDC_EMAIL                       1200
#define IDC_EMAILUSE                    1201
#define IDC_BIFONT                      1202
#define IDC_EDIT1                       1206
#define IDC_EDIT2                       1207
#define IDC_EXT                         1207
#define IDC_COMBO1                      1208
#define IDC_EDIT3                       1208
#define IDC_COMBO2                      1209
#define IDC_BUTTON2                     1211
#define IDC_NEWVERCHECK                 1212
#define IDC_BUTTON3                     1212
#define IDC_NEWVERCHK                   1213
#define IDC_NEWVERCHECK2                1213
#define IDC_CLEARLANG                   1214
#define IDC_RECENT                      1215
#define IDC_BUTTON6                     1215
#define IDC_URL_NEW                     1216
#define IDC_RADIO2                      1217
#define IDC_RADIO3                      1218
#define IDC_RADIO4                      1219
#define IDC_RADIO5                      1220
#define IDC_RADIO6                      1221
#define IDC_CHECK1                      1222
#define IDC_RADIO7                      1223
#define IDC_CHECK5                      1223
#define IDC_RADIO8                      1224
#define IDC_CHECK6                      1224
#define IDC_SLIDER1                     1225
#define IDC_SLIDER2                     1226
#define IDC_SLIDER3                     1227
#define IDC_RRATE                       1228
#define IDC_RADIO9                      1229
#define IDC_PLUGINVERS                  1229
#define IDC_RADIO10                     1230
#define IDC_SPLB                        1230
#define IDC_RADIO11                     1231
#define IDC_CHECK2                      1231
#define IDC_RADIO12                     1232
#define IDC_CHECK3                      1232
#define IDC_RADIO13                     1233
#define IDC_CHECK4                      1233
#define IDC_LIST1                       1234
#define IDC_EDIT4                       1235
#define IDC_TITLE                       1237
#define IDC_FILE                        1238
#define IDC_ALLOWMETRICS                1246
#define IDC_TEXT                        1247
#define IDC_MYPLAY                      1248
#define IDC_NC                          1249
#define IDC_RUNWINAMP                   1249
#define IDC_REGTEXT                     1250
#define IDC_PREFS_SHUFFLE_MORPH_RATE    1251
#define IDC_UNINST                      1252
#define IDC_PREFS_VIDEO_VSYNC           1253
#define IDC_PREFS_VIDEO_ADJASP          1254
#define IDC_PREFS_VIDEO_OVERLAYS        1255
#define IDC_PREFS_VIDEO_UPDSIZE         1256
#define IDC_PREFS_VIDEO_AUTOCLOSE       1257
#define IDC_PREFS_VIDEO_NOSS            1258
#define IDC_PREFS_VIDEO_OSD             1259
#define IDC_SCREENSHAPE1                1260
#define IDC_SCREENSHAPE2                1261
#define IDC_PREFS_VIDEO_YV12            1262
#define IDC_USE_SCREENSHAPE             1263
#define IDC_PREFS_VIDEO_STOPCLOSE       1264
#define IDC_PREFS_VIDEO_REMOVE_FS_ON_STOP 1265
#define IDC_PREFS_VIDEO_AUTOOPEN        1266
#define IDC_RENAME_SKIN                 1267
#define IDC_DELETE_SKIN                 1268
#define IDC_UNINSTVIS                   1269
#define IDC_UNINSTINPUT                 1270
#define IDC_UNINSTOUT                   1271
#define IDC_PROXY_ONLY_PORT_80          1272
#define IDC_WEBLINK                     1273
#define IDC_KEY                         1274
#define IDC_WEBLINK2                    1274
#define IDC_REGISTER                    1275
#define IDC_PROGRESS1                   1276
#define IDC_PROGRESS2                   1277
#define IDC_ABORT                       1278
#define IDC_TAB1                        1279
#define IDC_PLUGINLABEL                 1280
#define IDR_RESERVED_GENFF_1            1281
#define IDR_RESERVED_GENFF_2            1282
#define IDR_RESERVED_GENFF_3            1283
#define IDR_RESERVED_GENFF_4            1284
#define IDR_RESERVED_GENFF_5            1285
#define IDR_RESERVED_GENFF_6            1286
#define IDC_WATEXT1                     1287
#define IDC_WATEXT2                     1288
#define IDC_CUSTOMFONT                  1289
#define IDC_NOCUSTOMFONT                1290
#define IDC_STATIC_CUSTOMFONT           1291
#define IDC_FRAME1                      1292
#define IDC_ITEXT1                      1293
#define WINAMP_FILE_QUIT                40001
#define WINAMP_OPTIONS_PREFS            40012
#define WINAMP_OPTIONS_AOT              40019
#define WINAMP_FILE_REPEAT              40022
#define WINAMP_FILE_SHUFFLE             40023
#define WINAMP_HIGH_PRIORITY            40025
#define WINAMP_FILE_PLAY                40029
#define WINAMP_OPTIONS_EQ               40036
#define WINAMP_OPTIONS_ELAPSED          40037
#define WINAMP_OPTIONS_REMAINING        40038
#define WINAMP_OPTIONS_PLEDIT           40040
#define WINAMP_HELP_ABOUT               40041
#define WINAMP_MAINMENU                 40043
#define WINAMP_BUTTON1                  40044
#define WINAMP_BUTTON2                  40045
#define WINAMP_BUTTON3                  40046
#define WINAMP_BUTTON4                  40047
#define WINAMP_BUTTON5                  40048
#define WINAMP_VOLUMEUP                 40058
#define WINAMP_VOLUMEDOWN               40059
#define WINAMP_FFWD5S                   40060
#define WINAMP_REW5S                    40061
#define WINAMP_NEXT_WINDOW              40063
#define WINAMP_OPTIONS_WINDOWSHADE      40064
#define WINAMP_BUTTON1_SHIFT            40144
#define WINAMP_BUTTON2_SHIFT            40145
#define WINAMP_BUTTON3_SHIFT            40146
#define WINAMP_BUTTON4_SHIFT            40147
#define WINAMP_BUTTON5_SHIFT            40148
#define WINAMP_BUTTON1_CTRL             40154
#define WINAMP_BUTTON2_CTRL             40155
#define WINAMP_BUTTON3_CTRL             40156
#define WINAMP_BUTTON4_CTRL             40157
#define WINAMP_BUTTON5_CTRL             40158
#define WINAMP_OPTIONS_DSIZE            40165
#define IDC_SORT_FILENAME               40166
#define IDC_SORT_FILETITLE              40167
#define IDC_SORT_ENTIREFILENAME         40168
#define IDC_SELECTALL                   40169
#define IDC_SELECTNONE                  40170
#define IDC_SELECTINV                   40171
#define IDM_EQ_LOADPRE                  40172
#define IDM_EQ_LOADMP3                  40173
#define IDM_EQ_LOADDEFAULT              40174
#define IDM_EQ_SAVEPRE                  40175
#define IDM_EQ_SAVEMP3                  40176
#define IDM_EQ_SAVEDEFAULT              40177
#define IDM_EQ_DELPRE                   40178
#define IDM_EQ_DELMP3                   40180
#define IDC_PLAYLIST_PLAY               40184
#define WINAMP_FILE_LOC                 40185
#define WINAMP_OPTIONS_EASYMOVE         40186
#define WINAMP_FILE_DIR                 40187
#define WINAMP_EDIT_ID3                 40188
#define WINAMP_TOGGLE_AUTOSCROLL        40189
#define WINAMP_VISSETUP                 40190
#define WINAMP_PLGSETUP                 40191
#define WINAMP_VISPLUGIN                40192
#define WINAMP_JUMP                     40193
#define WINAMP_JUMPFILE                 40194
#define WINAMP_JUMP10FWD                40195
#define WINAMP_JUMP10BACK               40197
#define WINAMP_PREVSONG                 40198
#define WINAMP_OPTIONS_EXTRAHQ          40200
#define ID_PE_NEW                       40201
#define ID_PE_OPEN                      40202
#define ID_PE_SAVE                      40203
#define ID_PE_SAVEAS                    40204
#define ID_PE_SELECTALL                 40205
#define ID_PE_INVERT                    40206
#define ID_PE_NONE                      40207
#define ID_PE_ID3                       40208
#define ID_PE_S_TITLE                   40209
#define ID_PE_S_FILENAME                40210
#define ID_PE_S_PATH                    40211
#define ID_PE_S_RANDOM                  40212
#define ID_PE_S_REV                     40213
#define ID_PE_CLEAR                     40214
#define ID_PE_MOVEUP                    40215
#define ID_PE_MOVEDOWN                  40216
#define WINAMP_SELSKIN                  40219
#define WINAMP_VISCONF                  40221
#define ID_PE_NONEXIST                  40222
#define ID_PE_DELETEFROMDISK            40223
#define ID_PE_CLOSE                     40224
#define WINAMP_VIS_SETOSC               40226
#define WINAMP_VIS_SETANA               40227
#define WINAMP_VIS_SETOFF               40228
#define WINAMP_VIS_DOTSCOPE             40229
#define WINAMP_VIS_LINESCOPE            40230
#define WINAMP_VIS_SOLIDSCOPE           40231
#define WINAMP_VIS_NORMANA              40233
#define WINAMP_VIS_FIREANA              40234
#define WINAMP_VIS_LINEANA              40235
#define WINAMP_VIS_NORMVU               40236
#define WINAMP_VIS_SMOOTHVU             40237
#define WINAMP_VIS_FULLREF              40238
#define WINAMP_VIS_FULLREF2             40239
#define WINAMP_VIS_FULLREF3             40240
#define WINAMP_VIS_FULLREF4             40241
#define WINAMP_OPTIONS_TOGTIME          40242
#define EQ_ENABLE                       40244
#define EQ_AUTO                         40245
#define EQ_PRESETS                      40246
#define WINAMP_VIS_FALLOFF0             40247
#define WINAMP_VIS_FALLOFF1             40248
#define WINAMP_VIS_FALLOFF2             40249
#define WINAMP_VIS_FALLOFF3             40250
#define WINAMP_VIS_FALLOFF4             40251
#define WINAMP_VIS_PEAKS                40252
#define ID_LOAD_EQF                     40253
#define ID_SAVE_EQF                     40254
#define ID_PE_ENTRY                     40255
#define ID_PE_SCROLLUP                  40256
#define ID_PE_SCROLLDOWN                40257
#define WINAMP_MAIN_WINDOW              40258
#define WINAMP_VIS_PFALLOFF0            40259
#define WINAMP_VIS_PFALLOFF1            40260
#define WINAMP_VIS_PFALLOFF2            40261
#define WINAMP_VIS_PFALLOFF3            40262
#define WINAMP_VIS_PFALLOFF4            40263
#define ID_PE_TOP                       40264
#define ID_PE_BOTTOM                    40265
#define WINAMP_OPTIONS_WINDOWSHADE_PL   40266
#define EQ_INC1                         40267
#define EQ_INC2                         40268
#define EQ_INC3                         40269
#define EQ_INC4                         40270
#define EQ_INC5                         40271
#define EQ_INC6                         40272
#define EQ_INC7                         40273
#define EQ_INC8                         40274
#define EQ_INC9                         40275
#define EQ_INC10                        40276
#define EQ_INCPRE                       40277
#define EQ_DECPRE                       40278
#define EQ_DEC1                         40279
#define EQ_DEC2                         40280
#define EQ_DEC3                         40281
#define EQ_DEC4                         40282
#define EQ_DEC5                         40283
#define EQ_DEC6                         40284
#define EQ_DEC7                         40285
#define EQ_DEC8                         40286
#define EQ_DEC9                         40287
#define EQ_DEC10                        40288
#define ID_PE_SCUP                      40289
#define ID_PE_SCDOWN                    40290
#define WINAMP_REFRESHSKIN              40291
#define ID_PE_PRINT                     40292
#define ID_PE_EXTINFO                   40293
#define WINAMP_PLAYLIST_ADVANCE         40294
#define WINAMP_VIS_LIN                  40295
#define WINAMP_VIS_BAR                  40296
#define WINAMP_OPTIONS_MINIBROWSER      40298
#define MB_FWD                          40299
#define MB_BACK                         40300
#define MB_RELOAD                       40301
#define MB_OPENMENU                     40302
#define MB_OPENLOC                      40303
#define WINAMP_NEW_INSTANCE             40305
#define MB_UPDATE                       40309
#define WINAMP_OPTIONS_WINDOWSHADE_EQ   40310
#define EQ_PANLEFT                      40313
#define EQ_PANRIGHT                     40314
#define WINAMP_GETMORESKINS             40316
#define WINAMP_VIS_OPTIONS              40317
#define WINAMP_PE_SEARCH                40318
#define ID_PE_BOOKMARK                  40319
#define WINAMP_EDIT_BOOKMARKS           40320
#define WINAMP_MAKECURBOOKMARK          40321
#define ID_MAIN_PLAY_BOOKMARK_NONE      40322
#define ID_MAIN_PLAY_AUDIOCD            40323
#define ID_MAIN_PLAY_AUDIOCD2           40324
#define ID_MAIN_PLAY_AUDIOCD3           40325
#define ID_MAIN_PLAY_AUDIOCD4           40326
#define WINAMP_OPTIONS_VIDEO            40328
#define ID_VIDEOWND_ZOOMFULLSCREEN      40329
#define ID_VIDEOWND_ZOOM100             40330
#define ID_VIDEOWND_ZOOM200             40331
#define ID_VIDEOWND_ZOOM50              40332
#define ID_VIDEOWND_VIDEOOPTIONS        40333
#define WINAMP_MINIMIZE                 40334
#define ID_PE_FONTBIGGER                40335
#define ID_PE_FONTSMALLER               40336
#define WINAMP_VIDEO_TOGGLE_FS          40337
#define WINAMP_VIDEO_TVBUTTON           40338
#define WINAMP_LIGHTNING_CLICK          40339
#define ID_FILE_ADDTOLIBRARY            40344
#define ID_HELP_HELPTOPICS              40347
#define ID_HELP_GETTINGSTARTED          40348
#define ID_HELP_WINAMPFORUMS            40349
#define ID_PLAY_VOLUMEUP                40351
#define ID_PLAY_VOLUMEDOWN              40352
#define ID_PEFILE_OPENPLAYLISTFROMLIBRARY_NOPLAYLISTSINLIBRARY 40355
#define ID_PEFILE_ADDFROMLIBRARY        40356
#define ID_PEFILE_CLOSEPLAYLISTEDITOR   40357
#define ID_PEPLAYLIST_PLAYLISTPREFERENCES 40358
#define ID_MLFILE_NEWPLAYLIST           40359
#define ID_MLFILE_LOADPLAYLIST          40360
#define ID_MLFILE_SAVEPLAYLIST          40361
#define ID_MLFILE_ADDMEDIATOLIBRARY     40362
#define ID_MLFILE_CLOSEMEDIALIBRARY     40363
#define ID_MLVIEW_NOWPLAYING            40364
#define ID_MLVIEW_LOCALMEDIA_ALLMEDIA   40366
#define ID_MLVIEW_LOCALMEDIA_AUDIO      40367
#define ID_MLVIEW_LOCALMEDIA_VIDEO      40368
#define ID_MLVIEW_PLAYLISTS_NOPLAYLISTINLIBRARY 40369
#define ID_MLVIEW_INTERNETRADIO         40370
#define ID_MLVIEW_INTERNETTV            40371
#define ID_MLVIEW_LIBRARYPREFERENCES    40372
#define ID_MLVIEW_DEVICES_NOAVAILABLEDEVICE 40373
#define ID_MLFILE_IMPORTCURRENTPLAYLIST 40374
#define ID_MLVIEW_MEDIA                 40376
#define ID_MLVIEW_PLAYLISTS             40377
#define ID_MLVIEW_MEDIA_ALLMEDIA        40377
#define ID_MLVIEW_DEVICES               40378
#define ID_FILE_SHOWLIBRARY             40379
#define ID_FILE_CLOSELIBRARY            40380
#define ID_POST_PLAY_PLAYLIST           40381
#define ID_VIS_NEXT                     40382
#define ID_VIS_PREV                     40383
#define ID_VIS_RANDOM                   40384
#define ID_MANAGEPLAYLISTS              40385
#define ID_PREFS_SKIN_SWITCHTOSKIN      40386
#define ID_PREFS_SKIN_DELETESKIN        40387
#define ID_PREFS_SKIN_RENAMESKIN        40388
#define ID_VIS_FS                       40389
#define ID_VIS_CFG                      40390
#define ID_VIS_MENU                     40391
#define ID_VIS_SET_FS_FLAG              40392
#define ID_PE_SHOWPLAYING               40393
#define ID_HELP_REGISTERWINAMPPRO       40394

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        263
#define _APS_NEXT_COMMAND_VALUE         40395
#define _APS_NEXT_CONTROL_VALUE         1294
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
