//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by elektronika.rc
//
#define PNG_SNDMIX                      4
#define PNG_TEST                        102
#define PNG_TESTBUTTON                  103
#define PNG_ELEKTRONIKA                 104
#define PNG_SOUNDINPUT                  105
#define SWF_SPLASH                      108
#define PNG_MIRE_NB_220                 109
#define PNG_VIDEOOUT                    111
#define PNG_AESTESIS                    112
#define PNG_AESTESIS2                   113
#define PNG_SOUNDINPUT2                 115
#define PNG_VIDEOOUT2                   116
#define PNG_BUTTONDISK                  117
#define PNG_BUTTONPROP                  118
#define PNG_BUTTONFIRST                 119
#define PNG_BUTTONFWRD                  120
#define PNG_BUTTONLAST                  121
#define PNG_BUTTONPLAY                  122
#define PNG_BUTTONREC                   123
#define PNG_BUTTONREWIND                124
#define PNG_BUTTONSTOP                  125
#define PNG_AESTESIS_FORMS              127
#define PNG_AESTESIS_SOURCES            128
#define PNG_AESTESIS_COLORS             129
#define PNG_RHYTMBOX                    130
#define PNG_RHYTMBOX2                   131
#define PNG_RHYTMBOX_OPEN               132
#define PNG_RHYTMBOX_TRIGER             133
#define PNG_RHYTMBOX_SELECT             134
#define PNG_RHYTMBOX_LOOP               135
#define PNG_RHYTMBOX_PATTERN_SWITCH     136
#define PNG_RHYTMBOX_PATTERN            137
#define PNG_VMIX                        138
#define PNG_VMIX2                       139
#define PNG_VMIX_SOURCES                140
#define PNG_VMIX_TRANS                  141
#define PNG_TRANSSLICE_INV              155
#define PNG_TRANSSLICE_FADE             159
#define PNG_GRAB                        160
#define PNG_GRAB2                       161
#define PNG_WEBSRV                      162
#define PNG_WEBSRV2                     163
#define PNG_DVCAP2                      166
#define PNG_DVCAP                       167
#define PNG_RHYTMBOX_SOLO               168
#define PNG_RHYTMBOX_MUTE               169
#define PNG_TEXTURE001                  170
#define PNG_TEXTURE007                  171
#define PNG_TEXTURE003                  172
#define PNG_TEXTURE004                  173
#define PNG_TEXTURE005                  174
#define PNG_TEXTURE006                  175
#define PNG_TEXTURE002                  176
#define TXT_LICENSEDEMO                 177
#define PNG_SPHERE                      178
#define PNG_SPHERE2                     179
#define PNG_SPHERE_VERT                 180
#define PNG_SPHERE_DIAG                 181
#define PNG_SPHERE_HORZ                 182
#define PNG_SPHERE_CROSS                183
#define TXT_LICENSELIVE                 185
#define IDI_ICON1                       186
#define PNG_SOUNDOUTPUT2                187
#define PNG_SOUNDOUTPUT                 188
#define PNG_DISPATCH2                   189
#define PNG_DISPATCH                    190
#define PNG_LOOP2                       191
#define PNG_LOOP                        192
#define PNG_LOOP_SHAPE                  193
#define PNG_MIMIX_SELECT                194
#define PNG_MIMIX2                      195
#define PNG_MIMIX                       196
#define PNG_NETWORK2                    198
#define PNG_NETWORK                     199
#define PNG_NETWORK_BROWSE              200
#define PNG_WEBCLT2                     201
#define PNG_WEBCLT                      202
#define PNG_VIDEO3DOUT                  207
#define PNG_VIDEO3DOUT2                 208
#define PNG_EF3D_SOURCE                 209
#define PNG_EF3D_BLEND                  210
#define PNG_V3DOUT_EFFECTS              211
#define PNG_MORPH                       212
#define PNG_MORPH2                      213
#define PNG_WMPBACK                     214
#define PNG_WMPFRONT                    215
#define PNG_VPONE_RATE                  216
#define PNG_VPONE_FRONT                 217
#define PNG_VPONE_BACK                  218
#define PNG_VPONE_STOP                  220
#define PNG_VPONE_MOVIE                 221
#define PNG_VPONE_PLAY                  222
#define PNG_VPONE_MIRE                  223
#define PNG_VPONE_NOSNAP                224
#define PNG_VPONE_STATES                226
#define PNG_EF3D_VIDEO                  227
#define PNG_EF3D_META                   228
#define PNG_EF3D_ZOOM                   229
#define PNG_VPONE_BUTTON                230
#define PNG_AUTOMIX_FRONT               231
#define PNG_AUTOMIX_BACK                232
#define PNG_AUTOMIX_COLOR               233
#define PNG_AUTOMIX_BUTTON              234
#define PNG_AUTOMIX_BUTTON2             235
#define PNG_COLOR_FRONT                 236
#define PNG_COLOR_BACK                  237
#define PNG_VIDEOIN_FRONT               238
#define PNG_VIDEOIN_BACK                239
#define PNG_FFRAME_FRONT                240
#define PNG_FFRAME_BACK                 241
#define PNG_FFRAME_BUTTON               242
#define PNG_FFRAME_RST                  243
#define PNG_ELEKREG                     245
#define PNG_MIMIX_BLEND                 246
#define PNG_TRAIL_FRONT                 247
#define PNG_TRAIL_BACK                  248
#define PNG_RNBOX_BLEND                 250
#define PNG_RNBOX_SEQ3                  251
#define PNG_RNBOX_SEQ2                  252
#define PNG_RNBOX_SEQ1                  253
#define PNG_PIXSHAD                     254
#define PNG_LOOP_SELECT                 255
#define PNG_FLECHE_G                    257
#define PNG_FLECHE_D                    258
#define PNG_PUB_FRONT                   259
#define PNG_PUB_BACK                    260
#define PNG_FLECHE_GA                   261
#define PNG_FLECHE_DA                   262
#define PNG_PUB_TEXT                    263
#define PNG_PUB_IMAGE                   264
#define PNG_SOUNDINPUT_RIGHT            265
#define IDR_PNG2                        266
#define PNG_SOUNDINPUT_LEFT             266
#define PNG_ICONOPEN                    267
#define PNG_ICONSAVEAS                  268
#define PNG_ICONSAVE                    269
#define IDR_PNG5                        270
#define PNG_ICONNEW                     270
#define PNG_PRESET_STORE_SEL            271
#define PNG_PRESET_RECALL_ALL           272
#define PNG_PRESET_RECALL_SEL           273
#define PNG_PRESET_STORE_ALL            274
#define IDR_PNG1                        275
#define PNG_PRESET_DEL                  275
#define PNG_PUB_TEXT_POS                276
#define PNG_OMPPWRAP_FRONT              277
#define PNG_OMPPWRAP_BACK               278
#define PNG_OMPPWRAP_FONT               279
#define PNG_VIDEOIN_DEINTERLACE         280
#define PNG_VP10_FRONT                  281
#define PNG_VP10_BACK                   282
#define PNG_BUTMETAL                    283
#define PNG_BUTMETAL_7                  284
#define PNG_BUTMETAL_0                  285
#define PNG_BUTMETAL_1                  286
#define PNG_BUTMETAL_2                  287
#define PNG_BUTMETAL_3                  288
#define PNG_BUTMETAL_4                  289
#define PNG_BUTMETAL_5                  290
#define PNG_BUTMETAL_6                  291
#define PNG_BAND_FRONT                  292
#define PNG_BAND_BACK                   293
#define PNG_EF3D_ROTO                   294
#define PNG_VIS_FRONT                   295
#define PNG_VIS_BACK                    296
#define PNG_V3DOUT_DOWN                 297
#define PNG_V3DOUT_UP                   298
#define PNG_RNBOX_SEQ_MINI              299
#define PNG_RNBOX_SEQ4                  300
#define PNG_VMIX_STICK                  301
#define PNG_VMIX_PB                     302
#define PNG_VMIX_PA                     303
#define PNG_TRANSCOLOR_AB               304
#define PNG_VMIX_AUTO                   306
#define PNG_VMIX_SWITCH                 307
#define PNG_VMIX_CUT                    308
#define PNG_SLICE_AESTESIS              309
#define PNG_VMIX_FLIPY                  310
#define PNG_VMIX_FLIPX                  311
#define PNG_COLOR_PAL                   312
#define PNG_DISPATCH_SOURCES            313
#define PNG_SPHERE_SOURCES              314
#define PNG_ICONHELP                    315
#define PNG_BOLD                        316
#define IDR_PNG3                        317
#define PNG_ITALIC                      317
#define PNG_EF3D_TEXTTYPE               318
#define PNG_GRABWINBUT                  319
#define PNG_GRABCURSOR                  320
#define PNG_BUTMETAL_ALL                321
#define PNG_VP10PATTERN                 322
#define PNG_VP10_BUTTON                 323
#define PNG_VP10_BUTTON2                324
#define PNG_VP1_MIREOK                  326
#define PNG_VMIX_RAUTO                  327
#define PNG_VMIX_LAUTO                  328
#define PNG_DISP_TOOLBAR                329
#define PNG_VP10_PLAY                   330
#define PNG_VP10_SELSTEP                331
#define PNG_EXPORT_FRONT                332
#define PNG_EXPORT_BACK                 333
#define PNG_ELEKLIVE                    334
#define PNG_EXPORT_OPEN                 335
#define PNG_EF3DCUBE_SYM                336
#define PNG_EF3DCUBE                    337
#define PNG_EXPORTCAM                   338
#define PNG_EXPORT_AESTALPHA            340
#define PNG_EXPORT_AEST                 341
#define PNG_BUTEXPLORER                 342
#define PNG_REFRESH                     343
#define PNG_EXPORTCOMPPRESS             344
#define IDR_PNG4                        345
#define PNG_EXPORTFLIP                  345
#define PNG_V3DOUT_MASK                 346
#define IDB_PNG2                        347
#define IDB_PNG1                        348
#define PNG_V3DOUT_MASKICON             348
#define PNG_V3DOUT_DEFORM               65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        349
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
